version: '3'

services:
  api:
    build:
      context: .
      dockerfile: tools/dockerfile
    ports:
      - "8080:8080"
    environment:
      interval: 5
      async: "false"
      basePath: "/var"