FROM golang:latest as builder
RUN mkdir -p /app
WORKDIR /app
ENV GO111MODULE on
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN chmod +x /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build cmd/kvdb/main.go
FROM golang:latest
WORKDIR /root/
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app .
# Execite application when container is started
EXPOSE 80/tcp
CMD ["./main"]
EXPOSE 8080